version: '3.8'

services:
  backend:
    build: ./backend
    container_name: style-backend
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: always

  frontend:
    build: ./frontend
    container_name: style-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
